ALTER TABLE pacientes 
ADD bairro VARCHAR(100) NOT NULL DEFAULT '',
ADD logradouro VARCHAR(255) NOT NULL DEFAULT '',
ADD cep VARCHAR(9) NOT NULL DEFAULT '',
ADD complemento VARCHAR(100) NOT NULL DEFAULT '',
ADD numero VARCHAR(20) NOT NULL DEFAULT '',
ADD uf CHAR(2) NOT NULL DEFAULT '',
ADD cidade VARCHAR(100) NOT NULL DEFAULT '';
